// Copyright 2023 SGNL.ai, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/adapter/v1/adapter.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of the values for an attribute.
type AttributeType int32

const (
	// Invalid. Must not be used.
	AttributeType_ATTRIBUTE_TYPE_UNSPECIFIED AttributeType = 0
	// Boolean.
	AttributeType_ATTRIBUTE_TYPE_BOOL AttributeType = 1
	// Date or timestamp.
	AttributeType_ATTRIBUTE_TYPE_DATE_TIME AttributeType = 2
	// Double-precision float.
	AttributeType_ATTRIBUTE_TYPE_DOUBLE AttributeType = 3
	// Duration.
	AttributeType_ATTRIBUTE_TYPE_DURATION AttributeType = 4
	// Signed integer.
	AttributeType_ATTRIBUTE_TYPE_INT64 AttributeType = 5
	// String.
	AttributeType_ATTRIBUTE_TYPE_STRING AttributeType = 6
)

// Enum value maps for AttributeType.
var (
	AttributeType_name = map[int32]string{
		0: "ATTRIBUTE_TYPE_UNSPECIFIED",
		1: "ATTRIBUTE_TYPE_BOOL",
		2: "ATTRIBUTE_TYPE_DATE_TIME",
		3: "ATTRIBUTE_TYPE_DOUBLE",
		4: "ATTRIBUTE_TYPE_DURATION",
		5: "ATTRIBUTE_TYPE_INT64",
		6: "ATTRIBUTE_TYPE_STRING",
	}
	AttributeType_value = map[string]int32{
		"ATTRIBUTE_TYPE_UNSPECIFIED": 0,
		"ATTRIBUTE_TYPE_BOOL":        1,
		"ATTRIBUTE_TYPE_DATE_TIME":   2,
		"ATTRIBUTE_TYPE_DOUBLE":      3,
		"ATTRIBUTE_TYPE_DURATION":    4,
		"ATTRIBUTE_TYPE_INT64":       5,
		"ATTRIBUTE_TYPE_STRING":      6,
	}
)

func (x AttributeType) Enum() *AttributeType {
	p := new(AttributeType)
	*p = x
	return p
}

func (x AttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_adapter_v1_adapter_proto_enumTypes[0].Descriptor()
}

func (AttributeType) Type() protoreflect.EnumType {
	return &file_api_adapter_v1_adapter_proto_enumTypes[0]
}

func (x AttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttributeType.Descriptor instead.
func (AttributeType) EnumDescriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{0}
}

// Error codes indicating why the page request failed.
type ErrorCode int32

const (
	// Invalid. Must not be used.
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// Invalid page request config provided.
	ErrorCode_ERROR_CODE_INVALID_PAGE_REQUEST_CONFIG ErrorCode = 1
	// Invalid datasource config provided.
	ErrorCode_ERROR_CODE_INVALID_DATASOURCE_CONFIG ErrorCode = 2
	// Invalid datasource auth provided.
	ErrorCode_ERROR_CODE_INVALID_DATASOURCE_AUTH ErrorCode = 3
	// Invalid entity config provided.
	ErrorCode_ERROR_CODE_INVALID_ENTITY_CONFIG ErrorCode = 4
	// Unknown attribute provided in request.
	ErrorCode_ERROR_CODE_UNKNOWN_ATTRIBUTE ErrorCode = 5
	// Attribute returned from datasource does not match the expected type.
	ErrorCode_ERROR_CODE_INVALID_ATTRIBUTE_TYPE ErrorCode = 6
	// Datasource permanently unavailable.
	ErrorCode_ERROR_CODE_DATASOURCE_PERMANENTLY_UNAVAILABLE ErrorCode = 7
	// Datasource temporarily unavailable. Try again later.
	ErrorCode_ERROR_CODE_DATASOURCE_TEMPORARILY_UNAVAILABLE ErrorCode = 8
	// Failed to authenticate with datasource.
	ErrorCode_ERROR_CODE_DATASOURCE_AUTHENTICATION_FAILED ErrorCode = 9
	// Datasource failed unexpectedly.
	ErrorCode_ERROR_CODE_DATASOURCE_FAILED ErrorCode = 10
	// Unexpected failure due to the adapter implementation.
	ErrorCode_ERROR_CODE_INTERNAL ErrorCode = 11
	// Datasource received too many requests.
	ErrorCode_ERROR_CODE_DATASOURCE_TOO_MANY_REQUESTS ErrorCode = 12
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_INVALID_PAGE_REQUEST_CONFIG",
		2:  "ERROR_CODE_INVALID_DATASOURCE_CONFIG",
		3:  "ERROR_CODE_INVALID_DATASOURCE_AUTH",
		4:  "ERROR_CODE_INVALID_ENTITY_CONFIG",
		5:  "ERROR_CODE_UNKNOWN_ATTRIBUTE",
		6:  "ERROR_CODE_INVALID_ATTRIBUTE_TYPE",
		7:  "ERROR_CODE_DATASOURCE_PERMANENTLY_UNAVAILABLE",
		8:  "ERROR_CODE_DATASOURCE_TEMPORARILY_UNAVAILABLE",
		9:  "ERROR_CODE_DATASOURCE_AUTHENTICATION_FAILED",
		10: "ERROR_CODE_DATASOURCE_FAILED",
		11: "ERROR_CODE_INTERNAL",
		12: "ERROR_CODE_DATASOURCE_TOO_MANY_REQUESTS",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":                        0,
		"ERROR_CODE_INVALID_PAGE_REQUEST_CONFIG":        1,
		"ERROR_CODE_INVALID_DATASOURCE_CONFIG":          2,
		"ERROR_CODE_INVALID_DATASOURCE_AUTH":            3,
		"ERROR_CODE_INVALID_ENTITY_CONFIG":              4,
		"ERROR_CODE_UNKNOWN_ATTRIBUTE":                  5,
		"ERROR_CODE_INVALID_ATTRIBUTE_TYPE":             6,
		"ERROR_CODE_DATASOURCE_PERMANENTLY_UNAVAILABLE": 7,
		"ERROR_CODE_DATASOURCE_TEMPORARILY_UNAVAILABLE": 8,
		"ERROR_CODE_DATASOURCE_AUTHENTICATION_FAILED":   9,
		"ERROR_CODE_DATASOURCE_FAILED":                  10,
		"ERROR_CODE_INTERNAL":                           11,
		"ERROR_CODE_DATASOURCE_TOO_MANY_REQUESTS":       12,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_adapter_v1_adapter_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_adapter_v1_adapter_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{1}
}

// A request for a page of data.
type GetPageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The datasource the entity belongs to.
	Datasource *DatasourceConfig `protobuf:"bytes,1,opt,name=datasource,proto3" json:"datasource,omitempty"`
	// The entity to return a page of objects from.
	Entity *EntityConfig `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	// The maximum number of objects to return from the entity.
	// The number of child_objects in each object is not limited:
	// all the objects from child entities are returned in each parent object.
	PageSize int64 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The cursor that identifies the first object of the page to return, as
	// returned by the last call to GetPage for the entity.
	// If not set, return the first page for this entity.
	Cursor string `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// The tenant identifier associated with this request.
	// Optional.
	TenantId string `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The client identifier associated with this request.
	// Optional.
	ClientId      string `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageRequest) Reset() {
	*x = GetPageRequest{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageRequest) ProtoMessage() {}

func (x *GetPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageRequest.ProtoReflect.Descriptor instead.
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *GetPageRequest) GetDatasource() *DatasourceConfig {
	if x != nil {
		return x.Datasource
	}
	return nil
}

func (x *GetPageRequest) GetEntity() *EntityConfig {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *GetPageRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPageRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetPageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetPageRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// A response containing a page of data.
type GetPageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*GetPageResponse_Success
	//	*GetPageResponse_Error
	Response      isGetPageResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageResponse) Reset() {
	*x = GetPageResponse{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageResponse) ProtoMessage() {}

func (x *GetPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageResponse.ProtoReflect.Descriptor instead.
func (*GetPageResponse) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *GetPageResponse) GetResponse() isGetPageResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetPageResponse) GetSuccess() *Page {
	if x != nil {
		if x, ok := x.Response.(*GetPageResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *GetPageResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*GetPageResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetPageResponse_Response interface {
	isGetPageResponse_Response()
}

type GetPageResponse_Success struct {
	Success *Page `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type GetPageResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetPageResponse_Success) isGetPageResponse_Response() {}

func (*GetPageResponse_Error) isGetPageResponse_Response() {}

// The configuration of a datasource to get entity data from.
type DatasourceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the datasource.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The adapter-specific configuration for the datasource.
	// Optional.
	Config []byte `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// The address of the datasource.
	// Optional.
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// The credentials to use to authenticate with the datasource.
	// Optional.
	Auth *DatasourceAuthCredentials `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	// The type of the datasource. This can be used to route requests
	// on adapter deployments supporting multiple datasources.
	// If the adapter does not support this type, return an error.
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// On-Premises Connector Info associated with this datasource, if any.
	ConnectorInfo *ConnectorInfo `protobuf:"bytes,6,opt,name=connector_info,json=connectorInfo,proto3" json:"connector_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasourceConfig) Reset() {
	*x = DatasourceConfig{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasourceConfig) ProtoMessage() {}

func (x *DatasourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasourceConfig.ProtoReflect.Descriptor instead.
func (*DatasourceConfig) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *DatasourceConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DatasourceConfig) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DatasourceConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DatasourceConfig) GetAuth() *DatasourceAuthCredentials {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *DatasourceConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DatasourceConfig) GetConnectorInfo() *ConnectorInfo {
	if x != nil {
		return x.ConnectorInfo
	}
	return nil
}

type ConnectorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the connector.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The tenant identifier to which the connector is associated.
	TenantId string `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The client identifier to which the connector is associated.
	ClientId      string `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorInfo) Reset() {
	*x = ConnectorInfo{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorInfo) ProtoMessage() {}

func (x *ConnectorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorInfo.ProtoReflect.Descriptor instead.
func (*ConnectorInfo) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectorInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectorInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ConnectorInfo) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Credentials to use to authenticate with a datasource.
type DatasourceAuthCredentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The credentials to authenticate with the datasource.
	// Exactly one of these fields must be set.
	//
	// Types that are valid to be assigned to AuthMechanism:
	//
	//	*DatasourceAuthCredentials_Basic_
	//	*DatasourceAuthCredentials_HttpAuthorization
	AuthMechanism isDatasourceAuthCredentials_AuthMechanism `protobuf_oneof:"auth_mechanism"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasourceAuthCredentials) Reset() {
	*x = DatasourceAuthCredentials{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasourceAuthCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasourceAuthCredentials) ProtoMessage() {}

func (x *DatasourceAuthCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasourceAuthCredentials.ProtoReflect.Descriptor instead.
func (*DatasourceAuthCredentials) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{4}
}

func (x *DatasourceAuthCredentials) GetAuthMechanism() isDatasourceAuthCredentials_AuthMechanism {
	if x != nil {
		return x.AuthMechanism
	}
	return nil
}

func (x *DatasourceAuthCredentials) GetBasic() *DatasourceAuthCredentials_Basic {
	if x != nil {
		if x, ok := x.AuthMechanism.(*DatasourceAuthCredentials_Basic_); ok {
			return x.Basic
		}
	}
	return nil
}

func (x *DatasourceAuthCredentials) GetHttpAuthorization() string {
	if x != nil {
		if x, ok := x.AuthMechanism.(*DatasourceAuthCredentials_HttpAuthorization); ok {
			return x.HttpAuthorization
		}
	}
	return ""
}

type isDatasourceAuthCredentials_AuthMechanism interface {
	isDatasourceAuthCredentials_AuthMechanism()
}

type DatasourceAuthCredentials_Basic_ struct {
	// Basic authentication credentials.
	Basic *DatasourceAuthCredentials_Basic `protobuf:"bytes,1,opt,name=basic,proto3,oneof"`
}

type DatasourceAuthCredentials_HttpAuthorization struct {
	// Credentials to be sent in an HTTP Authorization header.
	// Must be prefixed with the scheme, e.g. "Bearer".
	HttpAuthorization string `protobuf:"bytes,2,opt,name=http_authorization,json=httpAuthorization,proto3,oneof"`
}

func (*DatasourceAuthCredentials_Basic_) isDatasourceAuthCredentials_AuthMechanism() {}

func (*DatasourceAuthCredentials_HttpAuthorization) isDatasourceAuthCredentials_AuthMechanism() {}

// The configuration of an entity to get data from.
type EntityConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the entity.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The adapter-specific name of the entity in the datasource.
	ExternalId string `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// Indicates whether the objects are ordered by ID, i.e. whether the
	// response must contain objects ordered by monotonically increasing IDs for
	// the entity.
	Ordered bool `protobuf:"varint,3,opt,name=ordered,proto3" json:"ordered,omitempty"`
	// The configuration of the attributes to return for the entity.
	Attributes []*AttributeConfig `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// The configuration of the entities that are children of the entity
	// to return together with the entity.
	ChildEntities []*EntityConfig `protobuf:"bytes,5,rep,name=child_entities,json=childEntities,proto3" json:"child_entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityConfig) Reset() {
	*x = EntityConfig{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityConfig) ProtoMessage() {}

func (x *EntityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityConfig.ProtoReflect.Descriptor instead.
func (*EntityConfig) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{5}
}

func (x *EntityConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityConfig) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *EntityConfig) GetOrdered() bool {
	if x != nil {
		return x.Ordered
	}
	return false
}

func (x *EntityConfig) GetAttributes() []*AttributeConfig {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *EntityConfig) GetChildEntities() []*EntityConfig {
	if x != nil {
		return x.ChildEntities
	}
	return nil
}

// The configuration of an attribute to ingest.
type AttributeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the attribute.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The adapter-specific name of the attribute in the entity.
	ExternalId string `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// The type of the ingested attribute's values.
	// Determines the field set in the returned AttributeValue for this
	// attribute.
	Type AttributeType `protobuf:"varint,3,opt,name=type,proto3,enum=sgnl.adapter.v1.AttributeType" json:"type,omitempty"`
	// Indicates whether the attribute contains a list of values vs. a single
	// value.
	List bool `protobuf:"varint,4,opt,name=list,proto3" json:"list,omitempty"`
	// Indicates whether the attribute represents a unique identifier for the entity.
	UniqueId      bool `protobuf:"varint,5,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeConfig) Reset() {
	*x = AttributeConfig{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeConfig) ProtoMessage() {}

func (x *AttributeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeConfig.ProtoReflect.Descriptor instead.
func (*AttributeConfig) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{6}
}

func (x *AttributeConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttributeConfig) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *AttributeConfig) GetType() AttributeType {
	if x != nil {
		return x.Type
	}
	return AttributeType_ATTRIBUTE_TYPE_UNSPECIFIED
}

func (x *AttributeConfig) GetList() bool {
	if x != nil {
		return x.List
	}
	return false
}

func (x *AttributeConfig) GetUniqueId() bool {
	if x != nil {
		return x.UniqueId
	}
	return false
}

// A page of objects returned from an entity.
type Page struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The set of objects in the page returned by the datasource for the
	// requested entity.
	// Up to page_size objects may be returned in this set.
	Objects []*Object `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	// The cursor that identifies the first object of the next page.
	// If not set, this page is the last page for this entity.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{7}
}

func (x *Page) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *Page) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// An object and its child objects.
type Object struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The object's attributes.
	Attributes []*Attribute `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// The child objects that belong to child entities of
	// the object's entity.
	ChildObjects  []*EntityObjects `protobuf:"bytes,2,rep,name=child_objects,json=childObjects,proto3" json:"child_objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{8}
}

func (x *Object) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Object) GetChildObjects() []*EntityObjects {
	if x != nil {
		return x.ChildObjects
	}
	return nil
}

// A set of objects belonging to the same entity.
type EntityObjects struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the entity the objects belong to.
	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// The set of objects.
	Objects       []*Object `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityObjects) Reset() {
	*x = EntityObjects{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityObjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityObjects) ProtoMessage() {}

func (x *EntityObjects) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityObjects.ProtoReflect.Descriptor instead.
func (*EntityObjects) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{9}
}

func (x *EntityObjects) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EntityObjects) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

// An attribute of an object.
type Attribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the attribute.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The value(s) of the attribute.
	// May contain more than one value only if list is true.
	// If no value is given, the attribute's value is null.
	Values        []*AttributeValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{10}
}

func (x *Attribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attribute) GetValues() []*AttributeValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// The value of an attribute.
type AttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AttributeValue_NullValue
	//	*AttributeValue_BoolValue
	//	*AttributeValue_DatetimeValue
	//	*AttributeValue_DoubleValue
	//	*AttributeValue_DurationValue
	//	*AttributeValue_Int64Value
	//	*AttributeValue_StringValue
	Value         isAttributeValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValue) Reset() {
	*x = AttributeValue{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValue) ProtoMessage() {}

func (x *AttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValue.ProtoReflect.Descriptor instead.
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{11}
}

func (x *AttributeValue) GetValue() isAttributeValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AttributeValue) GetNullValue() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_NullValue); ok {
			return x.NullValue
		}
	}
	return nil
}

func (x *AttributeValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *AttributeValue) GetDatetimeValue() *DateTime {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DatetimeValue); ok {
			return x.DatetimeValue
		}
	}
	return nil
}

func (x *AttributeValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *AttributeValue) GetDurationValue() *Duration {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DurationValue); ok {
			return x.DurationValue
		}
	}
	return nil
}

func (x *AttributeValue) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *AttributeValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

type isAttributeValue_Value interface {
	isAttributeValue_Value()
}

type AttributeValue_NullValue struct {
	NullValue *emptypb.Empty `protobuf:"bytes,1,opt,name=null_value,json=nullValue,proto3,oneof"`
}

type AttributeValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AttributeValue_DatetimeValue struct {
	DatetimeValue *DateTime `protobuf:"bytes,3,opt,name=datetime_value,json=datetimeValue,proto3,oneof"`
}

type AttributeValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type AttributeValue_DurationValue struct {
	DurationValue *Duration `protobuf:"bytes,5,opt,name=duration_value,json=durationValue,proto3,oneof"`
}

type AttributeValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,6,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type AttributeValue_StringValue struct {
	StringValue string `protobuf:"bytes,7,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*AttributeValue_NullValue) isAttributeValue_Value() {}

func (*AttributeValue_BoolValue) isAttributeValue_Value() {}

func (*AttributeValue_DatetimeValue) isAttributeValue_Value() {}

func (*AttributeValue_DoubleValue) isAttributeValue_Value() {}

func (*AttributeValue_DurationValue) isAttributeValue_Value() {}

func (*AttributeValue_Int64Value) isAttributeValue_Value() {}

func (*AttributeValue_StringValue) isAttributeValue_Value() {}

// A duration, as the sum of all the fields' durations.
// Each field may be positive, zero, or negative.
// The seconds and nanos fields have the same tags as in google.protobuf.Duration for backward compatibility:
// when only seconds and/or nanos are set in the message, it is marshaled identically to google.protobuf.Duration.
// The months and days fields are additions supported in Neo4j durations.
type Duration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A duration as a number of seconds.
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// A duration as a number of nanoseconds.
	Nanos int32 `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	// A duration as a number of months.
	Months int64 `protobuf:"varint,3,opt,name=months,proto3" json:"months,omitempty"`
	// A duration as a number of days.
	Days          int64 `protobuf:"varint,4,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{12}
}

func (x *Duration) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Duration) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

func (x *Duration) GetMonths() int64 {
	if x != nil {
		return x.Months
	}
	return 0
}

func (x *Duration) GetDays() int64 {
	if x != nil {
		return x.Days
	}
	return 0
}

// A date or timestamp.
type DateTime struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp in the UTC timezone.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The local timezone as its number of seconds east of UTC.
	// UTC if zero (default).
	TimezoneOffset int32 `protobuf:"varint,2,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DateTime) Reset() {
	*x = DateTime{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTime) ProtoMessage() {}

func (x *DateTime) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTime.ProtoReflect.Descriptor instead.
func (*DateTime) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{13}
}

func (x *DateTime) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DateTime) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

// An error retrieving a page.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The error message.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The error code indicating the cause of the error.
	Code ErrorCode `protobuf:"varint,2,opt,name=code,proto3,enum=sgnl.adapter.v1.ErrorCode" json:"code,omitempty"`
	// Recommended minimal duration after which this request may be retried. Optional.
	RetryAfter    *durationpb.Duration `protobuf:"bytes,3,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{14}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

// Basic authentication credentials.
type DatasourceAuthCredentials_Basic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasourceAuthCredentials_Basic) Reset() {
	*x = DatasourceAuthCredentials_Basic{}
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasourceAuthCredentials_Basic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasourceAuthCredentials_Basic) ProtoMessage() {}

func (x *DatasourceAuthCredentials_Basic) ProtoReflect() protoreflect.Message {
	mi := &file_api_adapter_v1_adapter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasourceAuthCredentials_Basic.ProtoReflect.Descriptor instead.
func (*DatasourceAuthCredentials_Basic) Descriptor() ([]byte, []int) {
	return file_api_adapter_v1_adapter_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DatasourceAuthCredentials_Basic) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DatasourceAuthCredentials_Basic) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_api_adapter_v1_adapter_proto protoreflect.FileDescriptor

const file_api_adapter_v1_adapter_proto_rawDesc = "" +
	"\n" +
	"\x1capi/adapter/v1/adapter.proto\x12\x0fsgnl.adapter.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\x0eGetPageRequest\x12A\n" +
	"\n" +
	"datasource\x18\x01 \x01(\v2!.sgnl.adapter.v1.DatasourceConfigR\n" +
	"datasource\x125\n" +
	"\x06entity\x18\x02 \x01(\v2\x1d.sgnl.adapter.v1.EntityConfigR\x06entity\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\"\x80\x01\n" +
	"\x0fGetPageResponse\x121\n" +
	"\asuccess\x18\x01 \x01(\v2\x15.sgnl.adapter.v1.PageH\x00R\asuccess\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x16.sgnl.adapter.v1.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xef\x01\n" +
	"\x10DatasourceConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12>\n" +
	"\x04auth\x18\x04 \x01(\v2*.sgnl.adapter.v1.DatasourceAuthCredentialsR\x04auth\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12E\n" +
	"\x0econnector_info\x18\x06 \x01(\v2\x1e.sgnl.adapter.v1.ConnectorInfoR\rconnectorInfo\"Y\n" +
	"\rConnectorInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\b \x01(\tR\bclientId\"\xe9\x01\n" +
	"\x19DatasourceAuthCredentials\x12H\n" +
	"\x05basic\x18\x01 \x01(\v20.sgnl.adapter.v1.DatasourceAuthCredentials.BasicH\x00R\x05basic\x12/\n" +
	"\x12http_authorization\x18\x02 \x01(\tH\x00R\x11httpAuthorization\x1a?\n" +
	"\x05Basic\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpasswordB\x10\n" +
	"\x0eauth_mechanism\"\xe1\x01\n" +
	"\fEntityConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x18\n" +
	"\aordered\x18\x03 \x01(\bR\aordered\x12@\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2 .sgnl.adapter.v1.AttributeConfigR\n" +
	"attributes\x12D\n" +
	"\x0echild_entities\x18\x05 \x03(\v2\x1d.sgnl.adapter.v1.EntityConfigR\rchildEntities\"\xa7\x01\n" +
	"\x0fAttributeConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.sgnl.adapter.v1.AttributeTypeR\x04type\x12\x12\n" +
	"\x04list\x18\x04 \x01(\bR\x04list\x12\x1b\n" +
	"\tunique_id\x18\x05 \x01(\bR\buniqueId\"Z\n" +
	"\x04Page\x121\n" +
	"\aobjects\x18\x01 \x03(\v2\x17.sgnl.adapter.v1.ObjectR\aobjects\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\x89\x01\n" +
	"\x06Object\x12:\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x1a.sgnl.adapter.v1.AttributeR\n" +
	"attributes\x12C\n" +
	"\rchild_objects\x18\x02 \x03(\v2\x1e.sgnl.adapter.v1.EntityObjectsR\fchildObjects\"_\n" +
	"\rEntityObjects\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x121\n" +
	"\aobjects\x18\x02 \x03(\v2\x17.sgnl.adapter.v1.ObjectR\aobjects\"T\n" +
	"\tAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\x06values\x18\x02 \x03(\v2\x1f.sgnl.adapter.v1.AttributeValueR\x06values\"\xe8\x02\n" +
	"\x0eAttributeValue\x127\n" +
	"\n" +
	"null_value\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\tnullValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12B\n" +
	"\x0edatetime_value\x18\x03 \x01(\v2\x19.sgnl.adapter.v1.DateTimeH\x00R\rdatetimeValue\x12#\n" +
	"\fdouble_value\x18\x04 \x01(\x01H\x00R\vdoubleValue\x12B\n" +
	"\x0eduration_value\x18\x05 \x01(\v2\x19.sgnl.adapter.v1.DurationH\x00R\rdurationValue\x12!\n" +
	"\vint64_value\x18\x06 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fstring_value\x18\a \x01(\tH\x00R\vstringValueB\a\n" +
	"\x05value\"f\n" +
	"\bDuration\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\x12\x16\n" +
	"\x06months\x18\x03 \x01(\x03R\x06months\x12\x12\n" +
	"\x04days\x18\x04 \x01(\x03R\x04days\"m\n" +
	"\bDateTime\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x0ftimezone_offset\x18\x02 \x01(\x05R\x0etimezoneOffset\"\x8d\x01\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12.\n" +
	"\x04code\x18\x02 \x01(\x0e2\x1a.sgnl.adapter.v1.ErrorCodeR\x04code\x12:\n" +
	"\vretry_after\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryAfter*\xd3\x01\n" +
	"\rAttributeType\x12\x1e\n" +
	"\x1aATTRIBUTE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ATTRIBUTE_TYPE_BOOL\x10\x01\x12\x1c\n" +
	"\x18ATTRIBUTE_TYPE_DATE_TIME\x10\x02\x12\x19\n" +
	"\x15ATTRIBUTE_TYPE_DOUBLE\x10\x03\x12\x1b\n" +
	"\x17ATTRIBUTE_TYPE_DURATION\x10\x04\x12\x18\n" +
	"\x14ATTRIBUTE_TYPE_INT64\x10\x05\x12\x19\n" +
	"\x15ATTRIBUTE_TYPE_STRING\x10\x06*\x93\x04\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12*\n" +
	"&ERROR_CODE_INVALID_PAGE_REQUEST_CONFIG\x10\x01\x12(\n" +
	"$ERROR_CODE_INVALID_DATASOURCE_CONFIG\x10\x02\x12&\n" +
	"\"ERROR_CODE_INVALID_DATASOURCE_AUTH\x10\x03\x12$\n" +
	" ERROR_CODE_INVALID_ENTITY_CONFIG\x10\x04\x12 \n" +
	"\x1cERROR_CODE_UNKNOWN_ATTRIBUTE\x10\x05\x12%\n" +
	"!ERROR_CODE_INVALID_ATTRIBUTE_TYPE\x10\x06\x121\n" +
	"-ERROR_CODE_DATASOURCE_PERMANENTLY_UNAVAILABLE\x10\a\x121\n" +
	"-ERROR_CODE_DATASOURCE_TEMPORARILY_UNAVAILABLE\x10\b\x12/\n" +
	"+ERROR_CODE_DATASOURCE_AUTHENTICATION_FAILED\x10\t\x12 \n" +
	"\x1cERROR_CODE_DATASOURCE_FAILED\x10\n" +
	"\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\v\x12+\n" +
	"'ERROR_CODE_DATASOURCE_TOO_MANY_REQUESTS\x10\f2Y\n" +
	"\aAdapter\x12N\n" +
	"\aGetPage\x12\x1f.sgnl.adapter.v1.GetPageRequest\x1a .sgnl.adapter.v1.GetPageResponse\"\x00B5Z3github.com/sgnl-ai/adapter-framework/api/adapter/v1b\x06proto3"

var (
	file_api_adapter_v1_adapter_proto_rawDescOnce sync.Once
	file_api_adapter_v1_adapter_proto_rawDescData []byte
)

func file_api_adapter_v1_adapter_proto_rawDescGZIP() []byte {
	file_api_adapter_v1_adapter_proto_rawDescOnce.Do(func() {
		file_api_adapter_v1_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_adapter_v1_adapter_proto_rawDesc), len(file_api_adapter_v1_adapter_proto_rawDesc)))
	})
	return file_api_adapter_v1_adapter_proto_rawDescData
}

var file_api_adapter_v1_adapter_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_adapter_v1_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_adapter_v1_adapter_proto_goTypes = []any{
	(AttributeType)(0),                      // 0: sgnl.adapter.v1.AttributeType
	(ErrorCode)(0),                          // 1: sgnl.adapter.v1.ErrorCode
	(*GetPageRequest)(nil),                  // 2: sgnl.adapter.v1.GetPageRequest
	(*GetPageResponse)(nil),                 // 3: sgnl.adapter.v1.GetPageResponse
	(*DatasourceConfig)(nil),                // 4: sgnl.adapter.v1.DatasourceConfig
	(*ConnectorInfo)(nil),                   // 5: sgnl.adapter.v1.ConnectorInfo
	(*DatasourceAuthCredentials)(nil),       // 6: sgnl.adapter.v1.DatasourceAuthCredentials
	(*EntityConfig)(nil),                    // 7: sgnl.adapter.v1.EntityConfig
	(*AttributeConfig)(nil),                 // 8: sgnl.adapter.v1.AttributeConfig
	(*Page)(nil),                            // 9: sgnl.adapter.v1.Page
	(*Object)(nil),                          // 10: sgnl.adapter.v1.Object
	(*EntityObjects)(nil),                   // 11: sgnl.adapter.v1.EntityObjects
	(*Attribute)(nil),                       // 12: sgnl.adapter.v1.Attribute
	(*AttributeValue)(nil),                  // 13: sgnl.adapter.v1.AttributeValue
	(*Duration)(nil),                        // 14: sgnl.adapter.v1.Duration
	(*DateTime)(nil),                        // 15: sgnl.adapter.v1.DateTime
	(*Error)(nil),                           // 16: sgnl.adapter.v1.Error
	(*DatasourceAuthCredentials_Basic)(nil), // 17: sgnl.adapter.v1.DatasourceAuthCredentials.Basic
	(*emptypb.Empty)(nil),                   // 18: google.protobuf.Empty
	(*timestamppb.Timestamp)(nil),           // 19: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),             // 20: google.protobuf.Duration
}
var file_api_adapter_v1_adapter_proto_depIdxs = []int32{
	4,  // 0: sgnl.adapter.v1.GetPageRequest.datasource:type_name -> sgnl.adapter.v1.DatasourceConfig
	7,  // 1: sgnl.adapter.v1.GetPageRequest.entity:type_name -> sgnl.adapter.v1.EntityConfig
	9,  // 2: sgnl.adapter.v1.GetPageResponse.success:type_name -> sgnl.adapter.v1.Page
	16, // 3: sgnl.adapter.v1.GetPageResponse.error:type_name -> sgnl.adapter.v1.Error
	6,  // 4: sgnl.adapter.v1.DatasourceConfig.auth:type_name -> sgnl.adapter.v1.DatasourceAuthCredentials
	5,  // 5: sgnl.adapter.v1.DatasourceConfig.connector_info:type_name -> sgnl.adapter.v1.ConnectorInfo
	17, // 6: sgnl.adapter.v1.DatasourceAuthCredentials.basic:type_name -> sgnl.adapter.v1.DatasourceAuthCredentials.Basic
	8,  // 7: sgnl.adapter.v1.EntityConfig.attributes:type_name -> sgnl.adapter.v1.AttributeConfig
	7,  // 8: sgnl.adapter.v1.EntityConfig.child_entities:type_name -> sgnl.adapter.v1.EntityConfig
	0,  // 9: sgnl.adapter.v1.AttributeConfig.type:type_name -> sgnl.adapter.v1.AttributeType
	10, // 10: sgnl.adapter.v1.Page.objects:type_name -> sgnl.adapter.v1.Object
	12, // 11: sgnl.adapter.v1.Object.attributes:type_name -> sgnl.adapter.v1.Attribute
	11, // 12: sgnl.adapter.v1.Object.child_objects:type_name -> sgnl.adapter.v1.EntityObjects
	10, // 13: sgnl.adapter.v1.EntityObjects.objects:type_name -> sgnl.adapter.v1.Object
	13, // 14: sgnl.adapter.v1.Attribute.values:type_name -> sgnl.adapter.v1.AttributeValue
	18, // 15: sgnl.adapter.v1.AttributeValue.null_value:type_name -> google.protobuf.Empty
	15, // 16: sgnl.adapter.v1.AttributeValue.datetime_value:type_name -> sgnl.adapter.v1.DateTime
	14, // 17: sgnl.adapter.v1.AttributeValue.duration_value:type_name -> sgnl.adapter.v1.Duration
	19, // 18: sgnl.adapter.v1.DateTime.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 19: sgnl.adapter.v1.Error.code:type_name -> sgnl.adapter.v1.ErrorCode
	20, // 20: sgnl.adapter.v1.Error.retry_after:type_name -> google.protobuf.Duration
	2,  // 21: sgnl.adapter.v1.Adapter.GetPage:input_type -> sgnl.adapter.v1.GetPageRequest
	3,  // 22: sgnl.adapter.v1.Adapter.GetPage:output_type -> sgnl.adapter.v1.GetPageResponse
	22, // [22:23] is the sub-list for method output_type
	21, // [21:22] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_adapter_v1_adapter_proto_init() }
func file_api_adapter_v1_adapter_proto_init() {
	if File_api_adapter_v1_adapter_proto != nil {
		return
	}
	file_api_adapter_v1_adapter_proto_msgTypes[1].OneofWrappers = []any{
		(*GetPageResponse_Success)(nil),
		(*GetPageResponse_Error)(nil),
	}
	file_api_adapter_v1_adapter_proto_msgTypes[4].OneofWrappers = []any{
		(*DatasourceAuthCredentials_Basic_)(nil),
		(*DatasourceAuthCredentials_HttpAuthorization)(nil),
	}
	file_api_adapter_v1_adapter_proto_msgTypes[11].OneofWrappers = []any{
		(*AttributeValue_NullValue)(nil),
		(*AttributeValue_BoolValue)(nil),
		(*AttributeValue_DatetimeValue)(nil),
		(*AttributeValue_DoubleValue)(nil),
		(*AttributeValue_DurationValue)(nil),
		(*AttributeValue_Int64Value)(nil),
		(*AttributeValue_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_adapter_v1_adapter_proto_rawDesc), len(file_api_adapter_v1_adapter_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_adapter_v1_adapter_proto_goTypes,
		DependencyIndexes: file_api_adapter_v1_adapter_proto_depIdxs,
		EnumInfos:         file_api_adapter_v1_adapter_proto_enumTypes,
		MessageInfos:      file_api_adapter_v1_adapter_proto_msgTypes,
	}.Build()
	File_api_adapter_v1_adapter_proto = out.File
	file_api_adapter_v1_adapter_proto_goTypes = nil
	file_api_adapter_v1_adapter_proto_depIdxs = nil
}
