// Copyright 2025 SGNL.ai, Inc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/connector/v1/connector.proto

package v1

import (
	v1 "github.com/sgnl-ai/adapter-framework/pkg/grpc_proxy/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Log level
type LogEntry_Level int32

const (
	LogEntry_DEBUG LogEntry_Level = 0
	LogEntry_INFO  LogEntry_Level = 1
	LogEntry_WARN  LogEntry_Level = 2
	LogEntry_ERROR LogEntry_Level = 3
)

// Enum value maps for LogEntry_Level.
var (
	LogEntry_Level_name = map[int32]string{
		0: "DEBUG",
		1: "INFO",
		2: "WARN",
		3: "ERROR",
	}
	LogEntry_Level_value = map[string]int32{
		"DEBUG": 0,
		"INFO":  1,
		"WARN":  2,
		"ERROR": 3,
	}
)

func (x LogEntry_Level) Enum() *LogEntry_Level {
	p := new(LogEntry_Level)
	*p = x
	return p
}

func (x LogEntry_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogEntry_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_connector_v1_connector_proto_enumTypes[0].Descriptor()
}

func (LogEntry_Level) Type() protoreflect.EnumType {
	return &file_proto_connector_v1_connector_proto_enumTypes[0]
}

func (x LogEntry_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogEntry_Level.Descriptor instead.
func (LogEntry_Level) EnumDescriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{3, 0}
}

// Wrapper messages with request IDs for request/response correlate
type ConnectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ProxyRequest  *v1.Request            `protobuf:"bytes,2,opt,name=proxy_request,json=proxyRequest,proto3" json:"proxy_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorRequest) Reset() {
	*x = ConnectorRequest{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorRequest) ProtoMessage() {}

func (x *ConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorRequest.ProtoReflect.Descriptor instead.
func (*ConnectorRequest) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectorRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConnectorRequest) GetProxyRequest() *v1.Request {
	if x != nil {
		return x.ProxyRequest
	}
	return nil
}

type ConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ProxyResponse *v1.Response           `protobuf:"bytes,2,opt,name=proxy_response,json=proxyResponse,proto3" json:"proxy_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorResponse) Reset() {
	*x = ConnectorResponse{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorResponse) ProtoMessage() {}

func (x *ConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorResponse.ProtoReflect.Descriptor instead.
func (*ConnectorResponse) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectorResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConnectorResponse) GetProxyResponse() *v1.Response {
	if x != nil {
		return x.ProxyResponse
	}
	return nil
}

// LogBatch contains a batch of log entries from the connector
type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	DroppedCount  uint32                 `protobuf:"varint,5,opt,name=dropped_count,json=droppedCount,proto3" json:"dropped_count,omitempty"` // Count of logs dropped
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{2}
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LogBatch) GetDroppedCount() uint32 {
	if x != nil {
		return x.DroppedCount
	}
	return 0
}

// LogEntry represents a single log entry
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Level         LogEntry_Level         `protobuf:"varint,2,opt,name=level,proto3,enum=sgnl.connector.v1.LogEntry_Level" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	FieldsJson    string                 `protobuf:"bytes,4,opt,name=fields_json,json=fieldsJson,proto3" json:"fields_json,omitempty"` // Structured fields as JSON
	LoggerName    string                 `protobuf:"bytes,5,opt,name=logger_name,json=loggerName,proto3" json:"logger_name,omitempty"`
	Caller        string                 `protobuf:"bytes,6,opt,name=caller,proto3" json:"caller,omitempty"`                           // file:line
	StackTrace    string                 `protobuf:"bytes,7,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"` // Only for ERROR level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{3}
}

func (x *LogEntry) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *LogEntry) GetLevel() LogEntry_Level {
	if x != nil {
		return x.Level
	}
	return LogEntry_DEBUG
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFieldsJson() string {
	if x != nil {
		return x.FieldsJson
	}
	return ""
}

func (x *LogEntry) GetLoggerName() string {
	if x != nil {
		return x.LoggerName
	}
	return ""
}

func (x *LogEntry) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *LogEntry) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

var File_proto_connector_v1_connector_proto protoreflect.FileDescriptor

const file_proto_connector_v1_connector_proto_rawDesc = "" +
	"\n" +
	"\"proto/connector/v1/connector.proto\x12\x11sgnl.connector.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a$proto/grpc_proxy/v1/grpc_proxy.proto\"s\n" +
	"\x10ConnectorRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12@\n" +
	"\rproxy_request\x18\x02 \x01(\v2\x1b.sgnl.grpc_proxy.v1.RequestR\fproxyRequest\"w\n" +
	"\x11ConnectorResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12C\n" +
	"\x0eproxy_response\x18\x02 \x01(\v2\x1c.sgnl.grpc_proxy.v1.ResponseR\rproxyResponse\"f\n" +
	"\bLogBatch\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.sgnl.connector.v1.LogEntryR\aentries\x12#\n" +
	"\rdropped_count\x18\x05 \x01(\rR\fdroppedCount\"\xae\x02\n" +
	"\bLogEntry\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x127\n" +
	"\x05level\x18\x02 \x01(\x0e2!.sgnl.connector.v1.LogEntry.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vfields_json\x18\x04 \x01(\tR\n" +
	"fieldsJson\x12\x1f\n" +
	"\vlogger_name\x18\x05 \x01(\tR\n" +
	"loggerName\x12\x16\n" +
	"\x06caller\x18\x06 \x01(\tR\x06caller\x12\x1f\n" +
	"\vstack_trace\x18\a \x01(\tR\n" +
	"stackTrace\"1\n" +
	"\x05Level\x12\t\n" +
	"\x05DEBUG\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\b\n" +
	"\x04WARN\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032\xb8\x01\n" +
	"\x10ConnectorService\x12`\n" +
	"\rRelayRequests\x12$.sgnl.connector.v1.ConnectorResponse\x1a#.sgnl.connector.v1.ConnectorRequest\"\x00(\x010\x01\x12B\n" +
	"\tRelayLogs\x12\x1b.sgnl.connector.v1.LogBatch\x1a\x16.google.protobuf.Empty\"\x00B7Z5github.com/sgnl-ai/adapter-framework/pkg/connector/v1b\x06proto3"

var (
	file_proto_connector_v1_connector_proto_rawDescOnce sync.Once
	file_proto_connector_v1_connector_proto_rawDescData []byte
)

func file_proto_connector_v1_connector_proto_rawDescGZIP() []byte {
	file_proto_connector_v1_connector_proto_rawDescOnce.Do(func() {
		file_proto_connector_v1_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_connector_v1_connector_proto_rawDesc), len(file_proto_connector_v1_connector_proto_rawDesc)))
	})
	return file_proto_connector_v1_connector_proto_rawDescData
}

var file_proto_connector_v1_connector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_connector_v1_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_connector_v1_connector_proto_goTypes = []any{
	(LogEntry_Level)(0),       // 0: sgnl.connector.v1.LogEntry.Level
	(*ConnectorRequest)(nil),  // 1: sgnl.connector.v1.ConnectorRequest
	(*ConnectorResponse)(nil), // 2: sgnl.connector.v1.ConnectorResponse
	(*LogBatch)(nil),          // 3: sgnl.connector.v1.LogBatch
	(*LogEntry)(nil),          // 4: sgnl.connector.v1.LogEntry
	(*v1.Request)(nil),        // 5: sgnl.grpc_proxy.v1.Request
	(*v1.Response)(nil),       // 6: sgnl.grpc_proxy.v1.Response
	(*emptypb.Empty)(nil),     // 7: google.protobuf.Empty
}
var file_proto_connector_v1_connector_proto_depIdxs = []int32{
	5, // 0: sgnl.connector.v1.ConnectorRequest.proxy_request:type_name -> sgnl.grpc_proxy.v1.Request
	6, // 1: sgnl.connector.v1.ConnectorResponse.proxy_response:type_name -> sgnl.grpc_proxy.v1.Response
	4, // 2: sgnl.connector.v1.LogBatch.entries:type_name -> sgnl.connector.v1.LogEntry
	0, // 3: sgnl.connector.v1.LogEntry.level:type_name -> sgnl.connector.v1.LogEntry.Level
	2, // 4: sgnl.connector.v1.ConnectorService.RelayRequests:input_type -> sgnl.connector.v1.ConnectorResponse
	3, // 5: sgnl.connector.v1.ConnectorService.RelayLogs:input_type -> sgnl.connector.v1.LogBatch
	1, // 6: sgnl.connector.v1.ConnectorService.RelayRequests:output_type -> sgnl.connector.v1.ConnectorRequest
	7, // 7: sgnl.connector.v1.ConnectorService.RelayLogs:output_type -> google.protobuf.Empty
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_connector_v1_connector_proto_init() }
func file_proto_connector_v1_connector_proto_init() {
	if File_proto_connector_v1_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_connector_v1_connector_proto_rawDesc), len(file_proto_connector_v1_connector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_connector_v1_connector_proto_goTypes,
		DependencyIndexes: file_proto_connector_v1_connector_proto_depIdxs,
		EnumInfos:         file_proto_connector_v1_connector_proto_enumTypes,
		MessageInfos:      file_proto_connector_v1_connector_proto_msgTypes,
	}.Build()
	File_proto_connector_v1_connector_proto = out.File
	file_proto_connector_v1_connector_proto_goTypes = nil
	file_proto_connector_v1_connector_proto_depIdxs = nil
}
