// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/connector/v1/connector.proto

package v1

import (
	v1 "github.com/sgnl-ai/adapter-framework/pkg/grpc_proxy/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wrapper messages with request IDs for request/response correlate
type ConnectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ProxyRequest  *v1.Request            `protobuf:"bytes,2,opt,name=proxy_request,json=proxyRequest,proto3" json:"proxy_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorRequest) Reset() {
	*x = ConnectorRequest{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorRequest) ProtoMessage() {}

func (x *ConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorRequest.ProtoReflect.Descriptor instead.
func (*ConnectorRequest) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectorRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConnectorRequest) GetProxyRequest() *v1.Request {
	if x != nil {
		return x.ProxyRequest
	}
	return nil
}

type ConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ProxyResponse *v1.Response           `protobuf:"bytes,2,opt,name=proxy_response,json=proxyResponse,proto3" json:"proxy_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorResponse) Reset() {
	*x = ConnectorResponse{}
	mi := &file_proto_connector_v1_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorResponse) ProtoMessage() {}

func (x *ConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_v1_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorResponse.ProtoReflect.Descriptor instead.
func (*ConnectorResponse) Descriptor() ([]byte, []int) {
	return file_proto_connector_v1_connector_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectorResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConnectorResponse) GetProxyResponse() *v1.Response {
	if x != nil {
		return x.ProxyResponse
	}
	return nil
}

var File_proto_connector_v1_connector_proto protoreflect.FileDescriptor

const file_proto_connector_v1_connector_proto_rawDesc = "" +
	"\n" +
	"\"proto/connector/v1/connector.proto\x12\x11sgnl.connector.v1\x1a$proto/grpc_proxy/v1/grpc_proxy.proto\"s\n" +
	"\x10ConnectorRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12@\n" +
	"\rproxy_request\x18\x02 \x01(\v2\x1b.sgnl.grpc_proxy.v1.RequestR\fproxyRequest\"w\n" +
	"\x11ConnectorResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12C\n" +
	"\x0eproxy_response\x18\x02 \x01(\v2\x1c.sgnl.grpc_proxy.v1.ResponseR\rproxyResponse2t\n" +
	"\x10ConnectorService\x12`\n" +
	"\rRelayRequests\x12$.sgnl.connector.v1.ConnectorResponse\x1a#.sgnl.connector.v1.ConnectorRequest\"\x00(\x010\x01B7Z5github.com/sgnl-ai/adapter-framework/pkg/connector/v1b\x06proto3"

var (
	file_proto_connector_v1_connector_proto_rawDescOnce sync.Once
	file_proto_connector_v1_connector_proto_rawDescData []byte
)

func file_proto_connector_v1_connector_proto_rawDescGZIP() []byte {
	file_proto_connector_v1_connector_proto_rawDescOnce.Do(func() {
		file_proto_connector_v1_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_connector_v1_connector_proto_rawDesc), len(file_proto_connector_v1_connector_proto_rawDesc)))
	})
	return file_proto_connector_v1_connector_proto_rawDescData
}

var file_proto_connector_v1_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_connector_v1_connector_proto_goTypes = []any{
	(*ConnectorRequest)(nil),  // 0: sgnl.connector.v1.ConnectorRequest
	(*ConnectorResponse)(nil), // 1: sgnl.connector.v1.ConnectorResponse
	(*v1.Request)(nil),        // 2: sgnl.grpc_proxy.v1.Request
	(*v1.Response)(nil),       // 3: sgnl.grpc_proxy.v1.Response
}
var file_proto_connector_v1_connector_proto_depIdxs = []int32{
	2, // 0: sgnl.connector.v1.ConnectorRequest.proxy_request:type_name -> sgnl.grpc_proxy.v1.Request
	3, // 1: sgnl.connector.v1.ConnectorResponse.proxy_response:type_name -> sgnl.grpc_proxy.v1.Response
	1, // 2: sgnl.connector.v1.ConnectorService.RelayRequests:input_type -> sgnl.connector.v1.ConnectorResponse
	0, // 3: sgnl.connector.v1.ConnectorService.RelayRequests:output_type -> sgnl.connector.v1.ConnectorRequest
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_connector_v1_connector_proto_init() }
func file_proto_connector_v1_connector_proto_init() {
	if File_proto_connector_v1_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_connector_v1_connector_proto_rawDesc), len(file_proto_connector_v1_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_connector_v1_connector_proto_goTypes,
		DependencyIndexes: file_proto_connector_v1_connector_proto_depIdxs,
		MessageInfos:      file_proto_connector_v1_connector_proto_msgTypes,
	}.Build()
	File_proto_connector_v1_connector_proto = out.File
	file_proto_connector_v1_connector_proto_goTypes = nil
	file_proto_connector_v1_connector_proto_depIdxs = nil
}
