name: Codecov Upload Report
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CODE_COVERAGE_THRESHOLD: 60

jobs:
  upload-coverage-report:
    runs-on: ubuntu-latest
    steps:
      # CodeCov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
