// Copyright 2025 SGNL.ai, Inc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/grpc_proxy/v1/grpc_proxy.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request represents a request to be proxied
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*Request_HttpRequest
	//	*Request_SqlQueryReq
	//	*Request_LdapSearchRequest
	RequestType   isRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_grpc_proxy_v1_grpc_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proxy_v1_grpc_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetRequestType() isRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *Request) GetHttpRequest() *HTTPRequest {
	if x != nil {
		if x, ok := x.RequestType.(*Request_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

func (x *Request) GetSqlQueryReq() *SQLQueryRequest {
	if x != nil {
		if x, ok := x.RequestType.(*Request_SqlQueryReq); ok {
			return x.SqlQueryReq
		}
	}
	return nil
}

func (x *Request) GetLdapSearchRequest() *LDAPSearchRequest {
	if x != nil {
		if x, ok := x.RequestType.(*Request_LdapSearchRequest); ok {
			return x.LdapSearchRequest
		}
	}
	return nil
}

type isRequest_RequestType interface {
	isRequest_RequestType()
}

type Request_HttpRequest struct {
	HttpRequest *HTTPRequest `protobuf:"bytes,1,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

type Request_SqlQueryReq struct {
	SqlQueryReq *SQLQueryRequest `protobuf:"bytes,2,opt,name=sql_query_req,json=sqlQueryReq,proto3,oneof"`
}

type Request_LdapSearchRequest struct {
	LdapSearchRequest *LDAPSearchRequest `protobuf:"bytes,3,opt,name=ldap_search_request,json=ldapSearchRequest,proto3,oneof"`
}

func (*Request_HttpRequest) isRequest_RequestType() {}

func (*Request_SqlQueryReq) isRequest_RequestType() {}

func (*Request_LdapSearchRequest) isRequest_RequestType() {}

// Response represents a response from the proxy
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to ResponseType:
	//
	//	*Response_HttpResponse
	//	*Response_SqlQueryResponse
	//	*Response_LdapSearchResponse
	ResponseType  isResponse_ResponseType `protobuf_oneof:"response_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_grpc_proxy_v1_grpc_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proxy_v1_grpc_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetResponseType() isResponse_ResponseType {
	if x != nil {
		return x.ResponseType
	}
	return nil
}

func (x *Response) GetHttpResponse() *HTTPResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_HttpResponse); ok {
			return x.HttpResponse
		}
	}
	return nil
}

func (x *Response) GetSqlQueryResponse() *SQLQueryResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_SqlQueryResponse); ok {
			return x.SqlQueryResponse
		}
	}
	return nil
}

func (x *Response) GetLdapSearchResponse() *LDAPSearchResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*Response_LdapSearchResponse); ok {
			return x.LdapSearchResponse
		}
	}
	return nil
}

type isResponse_ResponseType interface {
	isResponse_ResponseType()
}

type Response_HttpResponse struct {
	HttpResponse *HTTPResponse `protobuf:"bytes,2,opt,name=http_response,json=httpResponse,proto3,oneof"`
}

type Response_SqlQueryResponse struct {
	SqlQueryResponse *SQLQueryResponse `protobuf:"bytes,3,opt,name=sql_query_response,json=sqlQueryResponse,proto3,oneof"`
}

type Response_LdapSearchResponse struct {
	LdapSearchResponse *LDAPSearchResponse `protobuf:"bytes,4,opt,name=ldap_search_response,json=ldapSearchResponse,proto3,oneof"`
}

func (*Response_HttpResponse) isResponse_ResponseType() {}

func (*Response_SqlQueryResponse) isResponse_ResponseType() {}

func (*Response_LdapSearchResponse) isResponse_ResponseType() {}

// ProxyRequestMessage represents a request to be proxied to a specific connector
type ProxyRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *Request               `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	ConnectorId   string                 `protobuf:"bytes,2,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequestMessage) Reset() {
	*x = ProxyRequestMessage{}
	mi := &file_proto_grpc_proxy_v1_grpc_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequestMessage) ProtoMessage() {}

func (x *ProxyRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proxy_v1_grpc_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequestMessage.ProtoReflect.Descriptor instead.
func (*ProxyRequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyRequestMessage) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ProxyRequestMessage) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *ProxyRequestMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ProxyRequestMessage) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

var File_proto_grpc_proxy_v1_grpc_proxy_proto protoreflect.FileDescriptor

const file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDesc = "" +
	"\n" +
	"$proto/grpc_proxy/v1/grpc_proxy.proto\x12\x12sgnl.grpc_proxy.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1eproto/grpc_proxy/v1/http.proto\x1a\x1dproto/grpc_proxy/v1/sql.proto\x1a\x1eproto/grpc_proxy/v1/ldap.proto\"\x83\x02\n" +
	"\aRequest\x12D\n" +
	"\fhttp_request\x18\x01 \x01(\v2\x1f.sgnl.grpc_proxy.v1.HTTPRequestH\x00R\vhttpRequest\x12I\n" +
	"\rsql_query_req\x18\x02 \x01(\v2#.sgnl.grpc_proxy.v1.SQLQueryRequestH\x00R\vsqlQueryReq\x12W\n" +
	"\x13ldap_search_request\x18\x03 \x01(\v2%.sgnl.grpc_proxy.v1.LDAPSearchRequestH\x00R\x11ldapSearchRequestB\x0e\n" +
	"\frequest_type\"\xac\x02\n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12G\n" +
	"\rhttp_response\x18\x02 \x01(\v2 .sgnl.grpc_proxy.v1.HTTPResponseH\x00R\fhttpResponse\x12T\n" +
	"\x12sql_query_response\x18\x03 \x01(\v2$.sgnl.grpc_proxy.v1.SQLQueryResponseH\x00R\x10sqlQueryResponse\x12Z\n" +
	"\x14ldap_search_response\x18\x04 \x01(\v2&.sgnl.grpc_proxy.v1.LDAPSearchResponseH\x00R\x12ldapSearchResponseB\x0f\n" +
	"\rresponse_type\"\xa9\x01\n" +
	"\x13ProxyRequestMessage\x125\n" +
	"\arequest\x18\x01 \x01(\v2\x1b.sgnl.grpc_proxy.v1.RequestR\arequest\x12!\n" +
	"\fconnector_id\x18\x02 \x01(\tR\vconnectorId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId2{\n" +
	"\fProxyService\x12k\n" +
	"\fProxyRequest\x12'.sgnl.grpc_proxy.v1.ProxyRequestMessage\x1a\x1c.sgnl.grpc_proxy.v1.Response\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/proxyB8Z6github.com/sgnl-ai/adapter-framework/pkg/grpc_proxy/v1b\x06proto3"

var (
	file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDescOnce sync.Once
	file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDescData []byte
)

func file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDescGZIP() []byte {
	file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDescOnce.Do(func() {
		file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDesc), len(file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDesc)))
	})
	return file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDescData
}

var file_proto_grpc_proxy_v1_grpc_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_grpc_proxy_v1_grpc_proxy_proto_goTypes = []any{
	(*Request)(nil),             // 0: sgnl.grpc_proxy.v1.Request
	(*Response)(nil),            // 1: sgnl.grpc_proxy.v1.Response
	(*ProxyRequestMessage)(nil), // 2: sgnl.grpc_proxy.v1.ProxyRequestMessage
	(*HTTPRequest)(nil),         // 3: sgnl.grpc_proxy.v1.HTTPRequest
	(*SQLQueryRequest)(nil),     // 4: sgnl.grpc_proxy.v1.SQLQueryRequest
	(*LDAPSearchRequest)(nil),   // 5: sgnl.grpc_proxy.v1.LDAPSearchRequest
	(*HTTPResponse)(nil),        // 6: sgnl.grpc_proxy.v1.HTTPResponse
	(*SQLQueryResponse)(nil),    // 7: sgnl.grpc_proxy.v1.SQLQueryResponse
	(*LDAPSearchResponse)(nil),  // 8: sgnl.grpc_proxy.v1.LDAPSearchResponse
}
var file_proto_grpc_proxy_v1_grpc_proxy_proto_depIdxs = []int32{
	3, // 0: sgnl.grpc_proxy.v1.Request.http_request:type_name -> sgnl.grpc_proxy.v1.HTTPRequest
	4, // 1: sgnl.grpc_proxy.v1.Request.sql_query_req:type_name -> sgnl.grpc_proxy.v1.SQLQueryRequest
	5, // 2: sgnl.grpc_proxy.v1.Request.ldap_search_request:type_name -> sgnl.grpc_proxy.v1.LDAPSearchRequest
	6, // 3: sgnl.grpc_proxy.v1.Response.http_response:type_name -> sgnl.grpc_proxy.v1.HTTPResponse
	7, // 4: sgnl.grpc_proxy.v1.Response.sql_query_response:type_name -> sgnl.grpc_proxy.v1.SQLQueryResponse
	8, // 5: sgnl.grpc_proxy.v1.Response.ldap_search_response:type_name -> sgnl.grpc_proxy.v1.LDAPSearchResponse
	0, // 6: sgnl.grpc_proxy.v1.ProxyRequestMessage.request:type_name -> sgnl.grpc_proxy.v1.Request
	2, // 7: sgnl.grpc_proxy.v1.ProxyService.ProxyRequest:input_type -> sgnl.grpc_proxy.v1.ProxyRequestMessage
	1, // 8: sgnl.grpc_proxy.v1.ProxyService.ProxyRequest:output_type -> sgnl.grpc_proxy.v1.Response
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_grpc_proxy_v1_grpc_proxy_proto_init() }
func file_proto_grpc_proxy_v1_grpc_proxy_proto_init() {
	if File_proto_grpc_proxy_v1_grpc_proxy_proto != nil {
		return
	}
	file_proto_grpc_proxy_v1_http_proto_init()
	file_proto_grpc_proxy_v1_sql_proto_init()
	file_proto_grpc_proxy_v1_ldap_proto_init()
	file_proto_grpc_proxy_v1_grpc_proxy_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_HttpRequest)(nil),
		(*Request_SqlQueryReq)(nil),
		(*Request_LdapSearchRequest)(nil),
	}
	file_proto_grpc_proxy_v1_grpc_proxy_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_HttpResponse)(nil),
		(*Response_SqlQueryResponse)(nil),
		(*Response_LdapSearchResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDesc), len(file_proto_grpc_proxy_v1_grpc_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpc_proxy_v1_grpc_proxy_proto_goTypes,
		DependencyIndexes: file_proto_grpc_proxy_v1_grpc_proxy_proto_depIdxs,
		MessageInfos:      file_proto_grpc_proxy_v1_grpc_proxy_proto_msgTypes,
	}.Build()
	File_proto_grpc_proxy_v1_grpc_proxy_proto = out.File
	file_proto_grpc_proxy_v1_grpc_proxy_proto_goTypes = nil
	file_proto_grpc_proxy_v1_grpc_proxy_proto_depIdxs = nil
}
