// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/grpc_proxy/v1/http.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StringValues for a list of string values.
type StringValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringValues) Reset() {
	*x = StringValues{}
	mi := &file_proto_grpc_proxy_v1_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringValues) ProtoMessage() {}

func (x *StringValues) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proxy_v1_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringValues.ProtoReflect.Descriptor instead.
func (*StringValues) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proxy_v1_http_proto_rawDescGZIP(), []int{0}
}

func (x *StringValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// HTTPRequest represents an HTTP request to be proxied
type HTTPRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Method        string                   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]*StringValues `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRequest) Reset() {
	*x = HTTPRequest{}
	mi := &file_proto_grpc_proxy_v1_http_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequest) ProtoMessage() {}

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proxy_v1_http_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequest.ProtoReflect.Descriptor instead.
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proxy_v1_http_proto_rawDescGZIP(), []int{1}
}

func (x *HTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPRequest) GetHeaders() map[string]*StringValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// HTTPResponse represents an HTTP response from the proxy
type HTTPResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	StatusCode    int32                    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]*StringValues `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResponse) Reset() {
	*x = HTTPResponse{}
	mi := &file_proto_grpc_proxy_v1_http_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponse) ProtoMessage() {}

func (x *HTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_proxy_v1_http_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponse.ProtoReflect.Descriptor instead.
func (*HTTPResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_proxy_v1_http_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HTTPResponse) GetHeaders() map[string]*StringValues {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_proto_grpc_proxy_v1_http_proto protoreflect.FileDescriptor

const file_proto_grpc_proxy_v1_http_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/grpc_proxy/v1/http.proto\x12\x12sgnl.grpc_proxy.v1\"&\n" +
	"\fStringValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xf1\x01\n" +
	"\vHTTPRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12F\n" +
	"\aheaders\x18\x03 \x03(\v2,.sgnl.grpc_proxy.v1.HTTPRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a\\\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .sgnl.grpc_proxy.v1.StringValuesR\x05value:\x028\x01\"\xea\x01\n" +
	"\fHTTPResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12G\n" +
	"\aheaders\x18\x02 \x03(\v2-.sgnl.grpc_proxy.v1.HTTPResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a\\\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .sgnl.grpc_proxy.v1.StringValuesR\x05value:\x028\x01B8Z6github.com/sgnl-ai/adapter-framework/pkg/grpc_proxy/v1b\x06proto3"

var (
	file_proto_grpc_proxy_v1_http_proto_rawDescOnce sync.Once
	file_proto_grpc_proxy_v1_http_proto_rawDescData []byte
)

func file_proto_grpc_proxy_v1_http_proto_rawDescGZIP() []byte {
	file_proto_grpc_proxy_v1_http_proto_rawDescOnce.Do(func() {
		file_proto_grpc_proxy_v1_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpc_proxy_v1_http_proto_rawDesc), len(file_proto_grpc_proxy_v1_http_proto_rawDesc)))
	})
	return file_proto_grpc_proxy_v1_http_proto_rawDescData
}

var file_proto_grpc_proxy_v1_http_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_grpc_proxy_v1_http_proto_goTypes = []any{
	(*StringValues)(nil), // 0: sgnl.grpc_proxy.v1.StringValues
	(*HTTPRequest)(nil),  // 1: sgnl.grpc_proxy.v1.HTTPRequest
	(*HTTPResponse)(nil), // 2: sgnl.grpc_proxy.v1.HTTPResponse
	nil,                  // 3: sgnl.grpc_proxy.v1.HTTPRequest.HeadersEntry
	nil,                  // 4: sgnl.grpc_proxy.v1.HTTPResponse.HeadersEntry
}
var file_proto_grpc_proxy_v1_http_proto_depIdxs = []int32{
	3, // 0: sgnl.grpc_proxy.v1.HTTPRequest.headers:type_name -> sgnl.grpc_proxy.v1.HTTPRequest.HeadersEntry
	4, // 1: sgnl.grpc_proxy.v1.HTTPResponse.headers:type_name -> sgnl.grpc_proxy.v1.HTTPResponse.HeadersEntry
	0, // 2: sgnl.grpc_proxy.v1.HTTPRequest.HeadersEntry.value:type_name -> sgnl.grpc_proxy.v1.StringValues
	0, // 3: sgnl.grpc_proxy.v1.HTTPResponse.HeadersEntry.value:type_name -> sgnl.grpc_proxy.v1.StringValues
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_grpc_proxy_v1_http_proto_init() }
func file_proto_grpc_proxy_v1_http_proto_init() {
	if File_proto_grpc_proxy_v1_http_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpc_proxy_v1_http_proto_rawDesc), len(file_proto_grpc_proxy_v1_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_grpc_proxy_v1_http_proto_goTypes,
		DependencyIndexes: file_proto_grpc_proxy_v1_http_proto_depIdxs,
		MessageInfos:      file_proto_grpc_proxy_v1_http_proto_msgTypes,
	}.Build()
	File_proto_grpc_proxy_v1_http_proto = out.File
	file_proto_grpc_proxy_v1_http_proto_goTypes = nil
	file_proto_grpc_proxy_v1_http_proto_depIdxs = nil
}
